name: Run tests and other quality checks

on: [pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ["3.11"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies and the package
        run: |
          python -m pip install --upgrade pip
          pip install -vvv .[test]
      - name: Run unit tests
        run: pytest --cov=qbench --cov-report=xml -k 'not awscreds and not aersim'
        env:
          QISKIT_IBM_TOKEN: ${{ secrets.QISKIT_IBM_TOKEN }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  run_quality_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - uses: actions/checkout@v2
      - name: Install dependencies and the package
        run: |
          python -m pip install --upgrade pip
          pip install .[test,dev]
      - name: Run pre-commit hook checks
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run -a
      - name: Run mypy
        run: |
          pip install types-PyYAML
          mypy --namespace-packages --ignore-missing-imports --explicit-package-bases qbench
